image: alpine
pages:
  stage: deploy
  script:
  - mkdir .public # . files/folders are ignored by cp by default
  - cp -r * .public
  - mv .public public
  - rm public/bird-nescio-update-site.zip # remove extra zip copy
  - apk add unzip
  - unzip bird-nescio-update-site.zip -d public/update-site/
  artifacts:
    paths:
    - public
  only:
  - master
