image: alpine
pages:
  stage: deploy
  script:
  - mkdir .public # . files/folders are ignored by cp by default
  - cp -r * .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master
